package com.votehub.security;
import com.votehub.entity.*; import com.votehub.repository.*; import com.votehub.util.Crypto; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import java.security.SecureRandom; import java.time.*;
@Service public class AuthService { final UserRepository users; final OtpRepository otps; final SessionRepository sessions; final AuditRepository audits; final PasswordEncoder encoder; final SecureRandom random=new SecureRandom(); public AuthService(UserRepository u,OtpRepository o,SessionRepository s,AuditRepository a,PasswordEncoder e){users=u;otps=o;sessions=s;audits=a;encoder=e;}
 public String registerVoter(String voterId,String name,LocalDate dob,String aadhaar,String email,String mobile,String password){ if(users.existsByVoterId(voterId)||users.existsByEmail(email)) throw new RuntimeException("Voter ID or email already registered"); if(Period.between(dob,LocalDate.now()).getYears()<18) throw new RuntimeException("Voter must be at least 18 years old"); User u=new User();u.role=User.Role.VOTER;u.voterId=voterId;u.fullName=name;u.dateOfBirth=dob;u.email=email;u.mobile=mobile;u.aadhaarHmac=Crypto.hmac(aadhaar);u.passwordHash=encoder.encode(password);users.save(u);return issueOtp(u); }
 public String registerAdmin(String emp,String name,String email,String mobile,String password){if(users.existsByEmployeeId(emp)||users.existsByEmail(email))throw new RuntimeException("Employee ID or email already registered");User u=new User();u.role=User.Role.ADMIN;u.employeeId=emp;u.fullName=name;u.email=email;u.mobile=mobile;u.passwordHash=encoder.encode(password);users.save(u);return issueOtp(u);}
 String issueOtp(User u){OtpVerification old=otps.findTopByUserIdAndVerifiedFalseOrderByCreatedAtDesc(u.id).orElse(null); if(old!=null)old.verified=true; int code=100000+random.nextInt(900000);OtpVerification o=new OtpVerification();o.user=u;o.otpHash=Crypto.sha256(String.valueOf(code));o.expiresAt=LocalDateTime.now().plusMinutes(5);otps.save(o);audit(u,"OTP_GENERATED","Demo OTP generated");return String.valueOf(code);}
 public void verify(String id,String otp){User u=users.findByVoterId(id).orElseGet(()->users.findByEmployeeId(id).orElseThrow(()->new RuntimeException("Account not found")));OtpVerification o=otps.findTopByUserIdAndVerifiedFalseOrderByCreatedAtDesc(u.id).orElseThrow(()->new RuntimeException("OTP not found"));if(o.expiresAt.isBefore(LocalDateTime.now()))throw new RuntimeException("OTP expired");if(o.attempts>=3)throw new RuntimeException("Maximum OTP attempts reached");o.attempts++;if(!o.otpHash.equals(Crypto.sha256(otp))) {otps.save(o);throw new RuntimeException("Invalid OTP");}o.verified=true;u.verified=true;users.save(u);otps.save(o);audit(u,"OTP_VERIFIED","Account verified");}
 public String login(String id,String password){User u=users.findByVoterId(id).orElseGet(()->users.findByEmployeeId(id).orElseThrow(()->new RuntimeException("Invalid credentials")));if(!u.verified||!u.active||!encoder.matches(password,u.passwordHash))throw new RuntimeException("Invalid credentials or account not verified");String raw=java.util.UUID.randomUUID()+"-"+java.util.UUID.randomUUID();SessionToken s=new SessionToken();s.user=u;s.tokenHash=Crypto.sha256(raw);s.expiresAt=LocalDateTime.now().plusHours(8);sessions.save(s);audit(u,"LOGIN","Successful login");return raw;}
 public User user(String raw){SessionToken s=sessions.findByTokenHash(Crypto.sha256(raw)).orElseThrow(()->new RuntimeException("Unauthorized"));if(s.expiresAt.isBefore(LocalDateTime.now()))throw new RuntimeException("Session expired");return s.user;} void audit(User u,String action,String d){AuditLog l=new AuditLog();l.actor=u;l.action=action;l.details=d;audits.save(l);}
}
