package com.votehub.service;
import com.votehub.entity.*; import com.votehub.repository.*; import com.votehub.security.AuthService; import com.votehub.util.Crypto; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class ElectionService {final ElectionRepository elections;final CandidateRepository candidates;final VotingAuthorizationRepository auths;final VoteRepository votes;final AuthService auth; public ElectionService(ElectionRepository e,CandidateRepository c,VotingAuthorizationRepository a,VoteRepository v,AuthService au){elections=e;candidates=c;auths=a;votes=v;auth=au;}
 public List<Election> all(){return elections.findAllByOrderByStartTimeDesc();} public Election one(Long id){return elections.findById(id).orElseThrow(()->new RuntimeException("Election not found"));} public List<Candidate> candidates(Long id){return candidates.findByElectionId(id);} 
 public Map<String,Object> room(Long id,String token){Election e=one(id);User u=auth.user(token);sync(e);boolean eligible=u.role==User.Role.VOTER && u.verified && Period.between(u.dateOfBirth,LocalDate.now()).getYears()>=e.minAge;var a=eligible?auths.findByElectionIdAndUserId(id,u.id).orElse(null):null;return Map.of("election",e,"eligible",eligible,"alreadyVoted",a!=null&&a.used,"votes",votes.countByElectionId(id),"candidates",candidates(id));}
 @Transactional public Map<String,Object> cast(Long eid,Long cid,String token){Election e=one(eid);User u=auth.user(token);sync(e);if(e.status==Election.Status.CLOSED||e.status==Election.Status.UPCOMING)throw new RuntimeException("Voting is not open");if(u.role!=User.Role.VOTER||!u.verified||Period.between(u.dateOfBirth,LocalDate.now()).getYears()<e.minAge)throw new RuntimeException("Not eligible");VotingAuthorization a=auths.findByElectionIdAndUserId(eid,u.id).orElseGet(()->{VotingAuthorization x=new VotingAuthorization();x.election=e;x.user=u;x.tokenHash=Crypto.sha256(java.util.UUID.randomUUID().toString());return auths.save(x);});if(a.used)throw new RuntimeException("You have already voted in this election");Candidate c=candidates.findById(cid).orElseThrow(()->new RuntimeException("Candidate not found"));if(!c.election.id.equals(eid))throw new RuntimeException("Candidate is not in this election");Vote v=new Vote();v.election=e;v.candidate=c;v.ballotTokenHash=a.tokenHash;votes.save(v);a.used=true;auths.save(a);return Map.of("success",true,"message","Vote recorded successfully","votes",votes.countByElectionId(eid));}
 public Map<String,Object> results(Long eid){Election e=one(eid);List<Object[]> rows=votes.counts(eid);Map<Long,Long> m=new HashMap<>();for(Object[] r:rows)m.put((Long)r[0],(Long)r[1]);List<Map<String,Object>> out=new ArrayList<>();for(Candidate c:candidates(eid))out.add(Map.of("candidateId",c.id,"name",c.name,"votes",m.getOrDefault(c.id,0L)));return Map.of("election",e,"totalVotes",votes.countByElectionId(eid),"results",out);}
 public void sync(Election e){var now=LocalDateTime.now(); if(now.isAfter(e.endTime)){e.status=Election.Status.CLOSED;}else if(now.isAfter(e.startTime)){e.status=e.endTime.minusMinutes(30).isBefore(now)?Election.Status.CLOSING_SOON:Election.Status.ACTIVE;}else e.status=Election.Status.UPCOMING;elections.save(e);}
}
